[project]
name = "hentai-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []


[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"